### ISSUE TITLE
ActiveX plugins on Win8-Win11

### ISSUE THREAD

**Issue by ShokaKurumi** [CleanFlash/installer#15]
(I appologize for my grammatical mistake because English isn't my main language.)
The original Flash Player ActiveX installer will install two versions, a legacy version for Windows XP - Windows 7 and a modern version for Windows 8 - Windows 11. But only the legacy version is included in this project. On Windows 8 or newer OS, the legacy version just installed. This may cause potential problems.

**Comment by darktohka** [comment]
This is on purpose. Theoretically speaking, the Windows XP - Windows 7 version should be the most compatible with all operating systems.

Are there any actual benefits to the Windows 8 - Windows 10 version? Are there any missing features for example in the version compiled with the Windows 7 SDKs?

**Comment by ShokaKurumi** [comment]
Here's a example: [On this page (I'm sorry but it's in Chinese)](http://news.cntv.cn/2015/02/16/VIDE1424072040888426.shtml) with legacy version of ActiveX Flash Player, there is only sounds. But with the modern version every thing just works.

**Comment by ShokaKurumi** [comment]
@darktohka There're some bugs with legacy Active X plugin and Windows 8 or newer OS.

**Comment by darktohka** [comment]
The new version of Clean Flash now only installs the legacy Active X plugin on Windows 7 and older.

**Comment by nima-amin** [comment]
So, this means, if you need the activx version of FP to run a screensaver or programme such as SWF Player or the Irfan View FP Plugin on Windows 10 you can no longer update?

**Comment by darktohka** [comment]
You can still update, there will be no problem.

This issue is about unintended behaviour that would install the wrong version of the ActiveX plugin on newer systems, as a special build exists for every Windows 8+ system.

Since this issue has been resolved, now, the correct version will be installed on BOTH Windows 7 and older AND Windows 8 and newer.

So, feel free to update!
