### ISSUE TITLE
Will this work on Microsoft Edge (legacy or chromium)?

### ISSUE THREAD

**Issue by kristibektashi** [CleanFlash/installer#22]

**Comment by darktohka** [comment]
It will work in the new Chromium-based Microsoft Edge under "IE Mode". Using IE Mode requires you to setup special rules in the registry, though, so it's not a worthwhile approach. It should work on the legacy Microsoft Edge by default.

I highly recommend you install Waterfox instead.

**Comment by kristibektashi** [comment]
> Using IE Mode requires you to setup special rules in the registry, though, so it's not a worthwhile approach.

No it doesn't. You can enable it by going to the 3 dot menu and clicking Settings > Default Browser
