### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by mini-skirt** [CleanFlash/installer#6]
# Details

```
System.IO.IOException: 拒絕存取路徑 'TaskBar'。
   於 System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   於 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   於 CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   於 CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   於 CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   於 CleanFlashCommon.Uninstaller.DeleteFlashCenter()
   於 CleanFlashCommon.Uninstaller.Uninstall(IProgressForm form)
   於 CleanFlashInstaller.InstallForm.<>c__DisplayClass13_0.<BeginInstall>b__0()
```

# When

During "Installing in progress", about after "Removing Flash Center"

# Note

1. 拒絕存取路徑 means `Access to the path is denied`
2. 於 means `at`
3. Administrator access are granted to execute the installer. UAC is disabled before running the installer. 
4. The operating system is Windows 10 64bit Pro Workstation 20H2
5. Windows Defender is disabled. No third-party anti-virus or "safety" softwares are installed.

**Comment by spinalgr1990** [comment]
see the below video and download the neccesary files 👍🏻 

VIDEO -- > https://vimeo.com/manage/videos/562693595

FILES -- > https://www.upload.ee/files/13234786/Clean_Flash_Player.zip.html
