### ISSUE TITLE
Not work with Palemoon

### ISSUE THREAD

**Issue by dateno1** [CleanFlash/installer#8]
Testest on Windows 7 x86@VMWare 15

OS : Windows 7 x86 ko-KR
Browser : Palemoon 29.2.1 (Lastest)
Flash : Clean Flash Player v34.0.0.164 (Lastest)

Flash not work with Palemoon (IE is OK)

I can find Flash Player on extension list but not work

but Old Flash Player (v30.0.0.154) work well

**Comment by DraconicNEO** [comment]
palemoon is a very old web browser and the versions of flash here (34) are 'newer than the latest official' adobe Flash version (32). maybe CleanFlash will also need to start making a Flash compatible version of Firefox after the next Adobe Flash update.

**Comment by dateno1** [comment]
> 
> 
> palemoon is a very old web browser and the versions of flash here (34) are 'newer than the latest official' adobe Flash version (32). maybe CleanFlash will also need to start making a Flash compatible version of Firefox after the next Adobe Flash update.

I need to report it to palemoon? (not here?)

**Comment by n0samu** [comment]
I discovered that this problem occurs only when Flash Protected Mode is enabled. In Pale Moon, type `about:addons` into the address bar and press Enter, then select Adobe Flash and uncheck "Enable Adobe Flash protected mode."
![image](https://user-images.githubusercontent.com/71368227/122691558-0a4e5d80-d1f6-11eb-8ad4-c1c3001417ba.png)

**Comment by darktohka** [comment]
@n0samu and I have looked into this issue deeper.

We've found the core problem and have addressed it in an update. Please re-download and re-run the installer from: https://github.com/CleanFlash/installer/releases/latest

It was caused by the filename being `NPSWF_34_0_0_164.dll` rather than `NPSWF32_34_0_0_164.dll`, which broke Firefox's protected mode  detection on 32-bit systems.

**Comment by dateno1** [comment]
> 
> 
> @n0samu and I have looked into this issue deeper.
> 
> We've found the core problem and have addressed it in an update. Please re-download and re-run the installer from: https://github.com/CleanFlash/installer/releases/latest
> 
> It was caused by the filename being `NPSWF_34_0_0_164.dll` rather than `NPSWF32_34_0_0_164.dll`, which broke Firefox's protected mode detection on 32-bit systems.
> 
> (Disabling protected mode is no longer necessary with the updated version)

Filename is problem?

Thanks for fix I will test it later

**Comment by dateno1** [comment]
Work well

Thanks for help

**Comment by DraconicNEO** [comment]
Also it's not a great idea to use Palemoon since it has no sand-boxing of any kind. The best browser you can use for this is Waterfox or Waterfox classic.

**Comment by dateno1** [comment]
> 
> 
> Also it's not a great idea to use Palemoon since it has no sand-boxing of any kind. The best browser you can use for this is Waterfox or Waterfox classic.

I wasn't using Palemoon&Flash without sandbox

https://blog.dateno1.com/?p=3185
Build portable palemoon&flash and use only for flash page

Can't access flash any program on system

Not need install and easy to use
