### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by shigerugo2021** [CleanFlash/installer#9]
System.IO.IOException: 拒絕存取路徑 'TaskBar'。
   於 System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   於 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   於 CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   於 CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   於 CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   於 CleanFlashCommon.Uninstaller.DeleteFlashCenter()
   於 CleanFlashCommon.Uninstaller.Uninstall(IProgressForm form)
   於 CleanFlashInstaller.InstallForm.<>c__DisplayClass13_0.<BeginInstall>b__0()
   
   
   tried latest version installer, install was not successful

**Comment by darktohka** [comment]
Hey, can you try the newest patch: https://github.com/CleanFlash/installer/releases/latest and let me know if it works now?

**Comment by shigerugo2021** [comment]
We are doing a university wide deployment, some are successful, some are having issues. 
Here's more error messages:

leanFlashCommon.InstallException: Failed to apply changes to registry: error code 1
錯誤: 存取登錄時發生錯誤。
於 CleanFlashCommon.RegistryManager.ApplyRegistry(String registryContents)
於 CleanFlashInstaller.Installer.Install(IProgressForm form, InstallFlags flags)
於 CleanFlashInstaller.InstallForm.<>c__DisplayClass13_0.<BeginInstall>b__0()

**Comment by darktohka** [comment]
More changes have been made: https://github.com/CleanFlash/installer/releases/latest

Please try this version and see if the registry errors still happen.

**Comment by tchoucky61** [comment]
It works like a charm. TY.

**Comment by shigerugo2021** [comment]
Thank you for all the help, the deployment seems to be working successfully.

**Comment by darktohka** [comment]
Great to hear that! You're welcome!
